_BASE_: auto.yml
reduce_on_plateau: false
noamopt: false
learning_rate: 0.000005
learning_rate_decay_start: -1
batch_size: 16
cached_tokens: coco-train-eos-idxs

self_critical_after: -1
structure_after: 15
train_sample_n: 5
structure_loss_weight: 1
structure_loss_type: new_self_critical

max_epochs: 40

checkpoint_path: auto42
