_BASE_: kd_copy1.yml
reduce_on_plateau: false
noamopt: false
learning_rate: 0.000005
learning_rate_decay_start: -1
batch_size: 16


self_critical_after: -1
structure_after: 20
train_sample_n: 5
structure_loss_weight: 1
structure_loss_type: new_self_critical

max_epochs: 40

checkpoint_path: /home/wangcx/ckp/kd_nscl
