_BASE_: uic_sd.yml
reduce_on_plateau: false
noamopt: false
learning_rate: 0.000005
learning_rate_decay_start: -1
batch_size: 10
cached_tokens: coco-train-kd80-idxs
input_json: data/cocotalk_stanza_kd80_syn_dep0.json
input_label_h5: data/cocotalk_stanza_kd80_syn_dep0_label.h5


self_critical_after: -1
structure_after: 14
train_sample_n: 5
structure_loss_weight: 1
structure_loss_type: new_self_critical

max_epochs: 40

checkpoint_path: UIC_sd_kd80_nscl
